export { default as Copyright } from './copyright/Copyright'
export { default as FooterNewsletter } from './footer/FooterNewsletter'
export { default as Header } from './header/Header'
export { default as Navbar } from './navbar/Navbar'
export { default as Spinner } from './spinner/Spinner'
export { default as WorkItem } from './work/Item'
export { default as WorkList } from './work/List'
